### ISSUE TITLE
Crash when set Date to nil

### ISSUE THREAD

**Issue by Haraguroicha** [d7laungani/DLLocalNotifications#23] opened 2019-03-09 19:03 UTC
Crash at:

https://github.com/d7laungani/DLLocalNotifications/blob/e4e483e13b16af0fb5f65618f6347f0d3aa0bee5/DLLocalNotifications/DLLocalNotifications.swift#L117

by following code

```swift
let notification = DLNotification(identifier: "", alertTitle: "", alertBody: "", date: nil, repeats: .none, soundName: "")
let scheduler = DLNotificationScheduler()
scheduler.scheduleNotification(notification: notification)
scheduler.scheduleAllNotifications()
```

**Comment by d7laungani** [comment] 2019-12-15 18:20
Well a notification cannot be scheduled if there is no date set because then it would not know when to set the notification. My question would be what do you want the expected behavior to be?

**Comment by d7laungani** [comment] 2021-01-20 14:23
Thank you for reporting. This is now fixed. It is no longer marked as optional.

**Closed by d7laungani** 2021-01-20 14:23 UTC
